# Generated by Django 5.0.4 on 2024-05-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='Mugisha', max_length=255)),
                ('othernames', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Gender', max_length=10)),
                ('telephonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('nationalidnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('passportnumber', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(default='Mugisha Richard', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telephonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_entry', models.IntegerField(help_text='Year of entry')),
                ('nationality', models.CharField(blank=True, help_text='nationality', max_length=255, null=True)),
                ('college', models.CharField(choices=[('COCIS', 'COCIS'), ('COBAMS', 'COBAMS'), ('CHUS', 'CHUS'), ('CHS', 'CHS'), ('CONAS', 'CONAS'), ('CEDAT', 'CEDAT'), ('CAES', 'CAES'), ('CEES', 'CEES'), ('SOL', 'SOL')], help_text='Choose your college', max_length=255)),
                ('time_of_study', models.CharField(choices=[('Day', 'Day'), ('Evening', 'Evening')], help_text='Choose time of study', max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('student_number', models.CharField(blank=True, help_text='Student number', max_length=12, null=True, unique=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical', models.BooleanField(default=False)),
                ('accomodation', models.BooleanField(default=False)),
                ('banking', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('examination', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('other_transcript', models.BooleanField(default=False, verbose_name='Transcript')),
                ('other', models.CharField(blank=True, help_text='Additional services not listed above', max_length=255)),
                ('student_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.studentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_data', models.BinaryField(blank=True, help_text='Fingerprint data', null=True)),
                ('student_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.studentdetails')),
            ],
        ),
    ]
