# Generated by Django 5.0.4 on 2024-05-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='othernames',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationalidnumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passportnumber',
        ),
    ]
