# Generated by Django 5.0.6 on 2024-06-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='student',
        ),
    ]
