# Generated by Django 5.0.6 on 2024-06-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_verificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='fingerprint_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fingerprint',
            name='student_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
