# Generated by Django 5.0.6 on 2024-06-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_guardian_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='time_of_study',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.guardian'),
        ),
    ]
