# Generated by Django 5.0.6 on 2024-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fingerprint_fingerprint_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='device_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='device_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
