# Generated by Django 5.0.6 on 2024-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_studentdetails_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='student_number',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='nin_and_passport',
            field=models.CharField(blank=True, help_text='NIN or Passport', max_length=255, null=True),
        ),
    ]
