# Generated by Django 5.0.6 on 2024-06-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fingerprint_device_model_fingerprint_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilepic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
