# Generated by Django 5.0.6 on 2024-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='student_number',
            field=models.CharField(blank=True, help_text='Student number', max_length=255, null=True, unique=True),
        ),
    ]
