# Generated by Django 5.0.6 on 2024-06-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_studentdetails_guardian_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetails',
            old_name='year_of_entry',
            new_name='yearOfEntry',
        ),
    ]
