# Generated by Django 5.0.6 on 2024-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_year_of_entry_studentdetails_yearofentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='nin_and_passport',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='passportNumber',
            field=models.CharField(blank=True, help_text='National ID number', max_length=20, null=True),
        ),
    ]
