# Generated by Django 5.0.6 on 2024-06-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_studentdetails_nin_and_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='passportNumber',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True),
        ),
    ]
