# Generated by Django 5.0.6 on 2024-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_studentdetails_passportnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email to which the OTP is sent', max_length=254)),
                ('otp', models.CharField(help_text='One-Time Password', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when OTP was created')),
                ('expires_at', models.DateTimeField(help_text='Expiration time of the OTP')),
                ('used', models.BooleanField(default=False, help_text='Indicates if the OTP has been used')),
            ],
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
