# Generated by Django 5.0.6 on 2024-06-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_otp_delete_fingerprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(blank=True, help_text='Expiration time of the OTP', null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(blank=True, help_text='One-Time Password', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='api.student'),
        ),
        migrations.AddField(
            model_name='otp',
            name='student_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='api.studentdetails'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='used',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if the OTP has been used', null=True),
        ),
    ]
