# Generated by Django 5.0.6 on 2024-06-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_otp_email_remove_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
