# Generated by Django 5.0.6 on 2024-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_otp_alter_guardian_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
