# Generated by Django 5.0.6 on 2024-06-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_guardian_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
