# Generated by Django 5.0.6 on 2024-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
