# Generated by Django 5.0.6 on 2024-06-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_otp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='rmugisha927@gmail.com', max_length=255),
        ),
    ]
