# Generated by Django 5.0.6 on 2024-06-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_otp_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
