# Generated by Django 5.0.6 on 2024-06-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateofbirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='telephonenumber',
        ),
        migrations.AddField(
            model_name='student',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True),
        ),
    ]
