# Generated by Django 5.0.6 on 2024-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_student_dateofbirth_remove_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentNumber', models.CharField(blank=True, help_text='Student number', max_length=50, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentNumber',
        ),
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Gender', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='Mugisha', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='telephonenumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
