# Generated by Django 5.0.6 on 2024-06-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_pin_remove_student_pin_remove_student_studentnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='student_details',
        ),
    ]
