# Generated by Django 5.0.6 on 2024-06-07 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_guardian_student_services_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='other',
        ),
    ]
