# Generated by Django 5.0.6 on 2024-06-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_pin_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='studentNumber',
        ),
    ]
