# Generated by Django 5.0.6 on 2024-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_pin_studentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True),
        ),
    ]
