# Generated by Django 5.0.6 on 2024-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_pin_studentnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='pin_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
