# Generated by Django 5.0.6 on 2024-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_pin_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True, unique=True),
        ),
    ]
