# Generated by Django 5.0.6 on 2024-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_pin_studentnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin_model',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True, unique=True),
        ),
    ]
