# Generated by Django 5.0.6 on 2024-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_pin_model_studentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin_model',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True),
        ),
    ]
