# Generated by Django 5.0.6 on 2024-06-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_pin_model_pin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin_model',
            name='pin_number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
