# Generated by Django 5.0.6 on 2024-06-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_pin_model_pin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin_model',
            name='pin_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pin_model',
            name='studentNumber',
            field=models.CharField(blank=True, help_text='Student number', max_length=50, null=True),
        ),
    ]
