# Generated by Django 5.0.6 on 2024-06-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_pin_model_pin_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='pin',
        ),
    ]
