# Generated by Django 5.0.6 on 2024-06-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_pin_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='studentNumber',
            new_name='registrationNumber',
        ),
    ]
