# Generated by Django 5.0.6 on 2024-06-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_rename_studentnumber_pin_registrationnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='registrationNumber',
            new_name='studentNumber',
        ),
    ]
