# Generated by Django 5.0.6 on 2024-06-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_registrationnumber_pin_studentnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(default='Mugisha', max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telephonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', help_text='Gender', max_length=10)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
