# Generated by Django 5.0.2 on 2024-03-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210207_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccess',
            fields=[
                ('ServiceID', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceName', models.CharField(max_length=255)),
                ('ServiceDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('SettingID', models.AutoField(primary_key=True, serialize=False)),
                ('SettingName', models.CharField(max_length=255)),
                ('SettingValue', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='user',
            name='FingerPrintID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='FirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='R1C@rd0$', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='RegistrationNumber',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserType',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Administrator', 'Administrator')], default='Student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default='Ricky', max_length=255),
        ),
        migrations.CreateModel(
            name='AccessLogs',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('AccessDateTime', models.DateTimeField()),
                ('AccessType', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout')], max_length=10)),
                ('AccessResult', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], max_length=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.user')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprints',
            fields=[
                ('FingerPrintID', models.AutoField(primary_key=True, serialize=False)),
                ('FingerPrintData', models.BinaryField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessRights',
            fields=[
                ('AccessRightID', models.AutoField(primary_key=True, serialize=False)),
                ('AccessLevel', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write'), ('Admin', 'Admin')], max_length=10)),
                ('ServiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.serviceaccess')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
