# Generated by Django 5.0.2 on 2024-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_serviceaccess_systemsettings_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprints',
            name='FingerPrintData',
            field=models.ImageField(upload_to=''),
        ),
    ]
