# Generated by Django 5.0.2 on 2024-03-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_fingerprints_fingerprintdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=255),
        ),
    ]
